global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['35.89.91.200:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['35.89.91.200:9092']

  - job_name: 'nifi'
    metrics_path: '/metrics/'
    scheme: 'http'
    static_configs:
      - targets: ['35.89.91.200:9094']
    scrape_timeout: 15s
    honor_labels: true
